be more gentle with outputting and errors in the script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+set -x            # print commands before execution
+set -o errexit    # always exit on error
+set -o pipefail   # honor exit codes when piping
+set -o nounset    # fail on unset variables
+
 echo This is the generate-docs buildpack
 
 git clone https://github.com/DefactoSoftware/detroit
